# 数据合并 concat

In [1]:
import numpy as np
import pandas as pd

* NumPy的concat

In [2]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)

[[8 5 2 4]
 [2 9 9 0]
 [6 2 1 3]]
[[0 4 5 3]
 [6 4 1 3]
 [1 2 9 9]]


In [3]:
np.concatenate([arr1, arr2])

array([[8, 5, 2, 4],
       [2, 9, 9, 0],
       [6, 2, 1, 3],
       [0, 4, 5, 3],
       [6, 4, 1, 3],
       [1, 2, 9, 9]])

In [4]:
np.concatenate([arr1, arr2], axis=1)

array([[8, 5, 2, 4, 0, 4, 5, 3],
       [2, 9, 9, 0, 6, 4, 1, 3],
       [6, 2, 1, 3, 1, 2, 9, 9]])

* Series上的concat

In [5]:
# index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    9
1    9
2    5
3    6
4    4
dtype: int32
5    1
6    9
7    2
8    5
dtype: int32
9     4
10    7
11    4
dtype: int32


In [6]:
pd.concat([ser_obj1, ser_obj2, ser_obj3])

0     9
1     9
2     5
3     6
4     4
5     1
6     9
7     2
8     5
9     4
10    7
11    4
dtype: int32

In [7]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1)

0    1    2
0   9.0  NaN  NaN
1   9.0  NaN  NaN
2   5.0  NaN  NaN
3   6.0  NaN  NaN
4   4.0  NaN  NaN
5   NaN  1.0  NaN
6   NaN  9.0  NaN
7   NaN  2.0  NaN
8   NaN  5.0  NaN
9   NaN  NaN  4.0
10  NaN  NaN  7.0
11  NaN  NaN  4.0

In [8]:
# index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    7
1    3
2    9
3    1
4    7
dtype: int32
0    6
1    1
2    4
3    7
dtype: int32
0    7
1    2
2    3
dtype: int32


In [9]:
pd.concat([ser_obj1, ser_obj2, ser_obj3])

0    7
1    3
2    9
3    1
4    7
0    6
1    1
2    4
3    7
0    7
1    2
2    3
dtype: int32

In [10]:
pd.concat([ser_obj1, ser_obj2, ser_obj3], axis=1, join='inner')

0  1  2
0  7  6  7
1  3  1  2
2  9  4  3

* DataFrame上的concat

In [11]:
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print(df_obj1)
print(df_obj2)

   A  B
a  1  6
b  1  0
c  1  6
   C  D
a  2  1
b  7  4


In [12]:
pd.concat([df_obj1, df_obj2])

A    B    C    D
a  1.0  6.0  NaN  NaN
b  1.0  0.0  NaN  NaN
c  1.0  6.0  NaN  NaN
a  NaN  NaN  2.0  1.0
b  NaN  NaN  7.0  4.0

In [13]:
pd.concat([df_obj1, df_obj2], axis=1)

A  B    C    D
a  1  6  2.0  1.0
b  1  0  7.0  4.0
c  1  6  NaN  NaN